#!/bin/bash
set -eux

pip install wollok-kernel

KERNEL_DIR=$(jupyter kernelspec list | awk '/wollok/ {print $2}')
test -d "$KERNEL_DIR"

cat > "$KERNEL_DIR/kernel.json" <<EOF
{
  "argv": ["python", "-m", "wollok_kernel", "-f", "{connection_file}"],
  "display_name": "Wollok",
  "language": "wollok",
        "debugger": False,
        "vscode": {
            "interpreter": {
                "hash": ""
            },
            "displayName": "Wollok",
            "language": "wollok",
            "name": "wollok",
            "mimetype": "text/x-wollok"
        },
        "kernelspec": {
            "name": "wollok",
            "display_name": "Wollok",
            "language": "wollok"
        }
    },
    "language_info": {
        "name": "wollok",
        "file_extension": ".wlk",
        "mimetype": "text/x-wollok",
        "version": "1.0",
        "codemirror_mode": {
            "name": "wollok",
            "mimetype": "text/x-wollok"
        },
        "pygments_lexer": "wollok",
        "nbconvert_exporter": "wollok"
    }
}
EOF

jupyter kernelspec list

cat "$KERNEL_DIR/kernel.json"