#!/bin/bash
set -eux

pip install wollok-kernel

KERNEL_DIR=$(jupyter kernelspec list | grep wollok | awk '{print $2}')

cat > "$KERNEL_DIR/kernel.json" <<EOF
{
  "argv": ["python", "-m", "wollok_kernel"],
  "display_name": "Wollok",
  "language": "python"
}
EOF

cd ~/.wollok-kernel || exit 1
npm install
