#!/bin/bash
set -eux

pip install wollok-kernel

KERNEL_DIR=$(jupyter kernelspec list | awk '/wollok/ {print $2}')
test -d "$KERNEL_DIR"

cat > "$KERNEL_DIR/kernel.json" <<EOF
{
  "argv": ["python", "-m", "wollok_kernel"],
  "display_name": "Wollok",
  "language": "python"
}
EOF
